# Environment
language: objective-c
os: osx
osx_image: xcode10.1
cache:
  - bundler
  - cocoapods
env:
  global:
    - XCODE_WORKSPACE=FacebookSwift.xcworkspace

# Branch Builds
branches:
  only:
    - master
    - release-1.0
    - core-conversion

# Build Stages
stages:
  - name: analysis

# Build Jobs
jobs:
  include:
    - stage: analysis
      name: Linting
      script: sh scripts/travis/swiftlint.sh
    - stage: analysis
      name: Unit Tests
      script: sh scripts/travis/unit_tests.sh

# Scripts
before_install: sh scripts/travis/before_install.sh
install: sh scripts/travis/install.sh
